#!/bin/sh
CURRENT_USER="$(git config user.name)"
BRANCH="$(git symbolic-ref --short HEAD)"

GIT_USER_EMAIL=$(git config user.email)

# Allow specific git user to bypass
if [ "$GIT_USER_EMAIL" = "AbuuArwa001" || "$GIT_USER_EMAIL" = "khalfanathman12@yahoo.com"]; then
  exit 0
fi
branch="$(git symbolic-ref --short HEAD)"

if [ "$branch" = "main" ] || [ "$branch" = "develop" ]; then
  echo "❌ ERROR: Direct pushing to '$branch' is disabled."
  echo "➡️  Use Git Flow and push from a 'feature/' or 'release/' branch."
  exit 1
fi

