#!/bin/sh

GIT_USER_EMAIL=$(git config user.email)
BRANCH=$(git symbolic-ref --short HEAD)

# Allow specific git user to bypass
if [ "$GIT_USER_EMAIL" = "AbuArwa001" ] || [ "$GIT_USER_EMAIL" = "khalfanathman12@yahoo.com" ]; then
  exit 0
fi

if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "develop" ]; then
  echo "❌ ERROR: You are on '$BRANCH' — direct commits are not allowed."
  echo "➡️  Use Git Flow: create a 'feature/' or 'release/' branch."
  exit 1
fi