#!/bin/sh

branch="$(git symbolic-ref --short HEAD)"

if [ "$branch" = "main" ] || [ "$branch" = "develop" ]; then
  echo "❌ ERROR: Direct pushing to '$branch' is disabled."
  echo "➡️  Use Git Flow and push from a 'feature/' or 'release/' branch."
  exit 1
fi

